// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateAccountReq struct {
	UserId int64 `json:"userId"`
}

type CreateAccountResp struct {
	Address string `json:"address"`
}

type GetBalanceReq struct {
	UserId   int64  `json:"userId"`
	Currency string `json:"currency"`
}

type GetBalanceResp struct {
	Balance string `json:"balance"`
}
