// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: wallet.proto

package walletclient

import (
	"context"

	"github.com/wwater/my-cex/app/wallet/rpc/wallet"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateWalletReq  = wallet.CreateWalletReq
	CreateWalletResp = wallet.CreateWalletResp
	GetBalanceReq    = wallet.GetBalanceReq
	GetBalanceResp   = wallet.GetBalanceResp

	Wallet interface {
		CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error)
		GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error)
	}

	defaultWallet struct {
		cli zrpc.Client
	}
)

func NewWallet(cli zrpc.Client) Wallet {
	return &defaultWallet{
		cli: cli,
	}
}

func (m *defaultWallet) CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.CreateWallet(ctx, in, opts...)
}

func (m *defaultWallet) GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.GetBalance(ctx, in, opts...)
}
