// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: wallet.proto

package walletclient

import (
	"context"

	"github.com/wwater/my-cex/app/wallet/rpc/wallet"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateWalletReq  = wallet.CreateWalletReq
	CreateWalletResp = wallet.CreateWalletResp
	DepositReq       = wallet.DepositReq
	DepositResp      = wallet.DepositResp
	GetBalanceReq    = wallet.GetBalanceReq
	GetBalanceResp   = wallet.GetBalanceResp
	WithdrawReq      = wallet.WithdrawReq
	WithdrawResp     = wallet.WithdrawResp

	Wallet interface {
		CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error)
		GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error)
		Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error)
		Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error)
	}

	defaultWallet struct {
		cli zrpc.Client
	}
)

func NewWallet(cli zrpc.Client) Wallet {
	return &defaultWallet{
		cli: cli,
	}
}

func (m *defaultWallet) CreateWallet(ctx context.Context, in *CreateWalletReq, opts ...grpc.CallOption) (*CreateWalletResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.CreateWallet(ctx, in, opts...)
}

func (m *defaultWallet) GetBalance(ctx context.Context, in *GetBalanceReq, opts ...grpc.CallOption) (*GetBalanceResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.GetBalance(ctx, in, opts...)
}

func (m *defaultWallet) Deposit(ctx context.Context, in *DepositReq, opts ...grpc.CallOption) (*DepositResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.Deposit(ctx, in, opts...)
}

func (m *defaultWallet) Withdraw(ctx context.Context, in *WithdrawReq, opts ...grpc.CallOption) (*WithdrawResp, error) {
	client := wallet.NewWalletClient(m.cli.Conn())
	return client.Withdraw(ctx, in, opts...)
}
