// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"github.com/wwater/my-cex/app/account/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/balance",
				Handler: GetBalanceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/create",
				Handler: CreateAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/deposit",
				Handler: DepositHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/account/logs",
				Handler: GetLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/withdraw",
				Handler: WithdrawHandler(serverCtx),
			},
		},
	)
}
