// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: wallet.proto

package server

import (
	"context"

	"github.com/wwater/my-cex/app/wallet/rpc/internal/logic"
	"github.com/wwater/my-cex/app/wallet/rpc/internal/svc"
	"github.com/wwater/my-cex/app/wallet/rpc/wallet"
)

type WalletServer struct {
	svcCtx *svc.ServiceContext
	wallet.UnimplementedWalletServer
}

func NewWalletServer(svcCtx *svc.ServiceContext) *WalletServer {
	return &WalletServer{
		svcCtx: svcCtx,
	}
}

func (s *WalletServer) CreateWallet(ctx context.Context, in *wallet.CreateWalletReq) (*wallet.CreateWalletResp, error) {
	l := logic.NewCreateWalletLogic(ctx, s.svcCtx)
	return l.CreateWallet(in)
}

func (s *WalletServer) GetBalance(ctx context.Context, in *wallet.GetBalanceReq) (*wallet.GetBalanceResp, error) {
	l := logic.NewGetBalanceLogic(ctx, s.svcCtx)
	return l.GetBalance(in)
}
