// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: app/wallet/rpc/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建钱包
type CreateWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletReq) Reset() {
	*x = CreateWalletReq{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletReq) ProtoMessage() {}

func (x *CreateWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletReq.ProtoReflect.Descriptor instead.
func (*CreateWalletReq) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 返回地址
type CreateWalletResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResp) Reset() {
	*x = CreateWalletResp{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResp) ProtoMessage() {}

func (x *CreateWalletResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResp.ProtoReflect.Descriptor instead.
func (*CreateWalletResp) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// 获取余额
type GetBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // 例如 "ETH"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceReq) Reset() {
	*x = GetBalanceReq{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceReq) ProtoMessage() {}

func (x *GetBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceReq.ProtoReflect.Descriptor instead.
func (*GetBalanceReq) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetBalanceReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetBalanceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResp) Reset() {
	*x = GetBalanceResp{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResp) ProtoMessage() {}

func (x *GetBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResp.ProtoReflect.Descriptor instead.
func (*GetBalanceResp) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResp) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetBalanceResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// 充值
type DepositReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TxId          string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositReq) Reset() {
	*x = DepositReq{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositReq) ProtoMessage() {}

func (x *DepositReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositReq.ProtoReflect.Descriptor instead.
func (*DepositReq) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *DepositReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *DepositReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DepositReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type DepositResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    string                 `protobuf:"bytes,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResp) Reset() {
	*x = DepositResp{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResp) ProtoMessage() {}

func (x *DepositResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResp.ProtoReflect.Descriptor instead.
func (*DepositResp) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *DepositResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DepositResp) GetNewBalance() string {
	if x != nil {
		return x.NewBalance
	}
	return ""
}

// 提现
type WithdrawReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`         // 金额
	TxId          string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"` // 业务流水号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawReq) Reset() {
	*x = WithdrawReq{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawReq) ProtoMessage() {}

func (x *WithdrawReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawReq.ProtoReflect.Descriptor instead.
func (*WithdrawReq) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *WithdrawReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *WithdrawReq) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawReq) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type WithdrawResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"` // 模拟返回一个链上哈希
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResp) Reset() {
	*x = WithdrawResp{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResp) ProtoMessage() {}

func (x *WithdrawResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResp.ProtoReflect.Descriptor instead.
func (*WithdrawResp) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WithdrawResp) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_app_wallet_rpc_wallet_proto protoreflect.FileDescriptor

const file_app_wallet_rpc_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1bapp/wallet/rpc/wallet.proto\x12\x06wallet\"#\n" +
	"\x0fCreateWalletReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\",\n" +
	"\x10CreateWalletResp\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"=\n" +
	"\rGetBalanceReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"F\n" +
	"\x0eGetBalanceResp\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"K\n" +
	"\n" +
	"DepositReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\"H\n" +
	"\vDepositResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\tR\n" +
	"newBalance\"L\n" +
	"\vWithdrawReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\"A\n" +
	"\fWithdrawResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash2\xf3\x01\n" +
	"\x06Wallet\x12A\n" +
	"\fCreateWallet\x12\x17.wallet.CreateWalletReq\x1a\x18.wallet.CreateWalletResp\x12;\n" +
	"\n" +
	"GetBalance\x12\x15.wallet.GetBalanceReq\x1a\x16.wallet.GetBalanceResp\x122\n" +
	"\aDeposit\x12\x12.wallet.DepositReq\x1a\x13.wallet.DepositResp\x125\n" +
	"\bWithdraw\x12\x13.wallet.WithdrawReq\x1a\x14.wallet.WithdrawRespB\n" +
	"Z\b./walletb\x06proto3"

var (
	file_app_wallet_rpc_wallet_proto_rawDescOnce sync.Once
	file_app_wallet_rpc_wallet_proto_rawDescData []byte
)

func file_app_wallet_rpc_wallet_proto_rawDescGZIP() []byte {
	file_app_wallet_rpc_wallet_proto_rawDescOnce.Do(func() {
		file_app_wallet_rpc_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_wallet_rpc_wallet_proto_rawDesc), len(file_app_wallet_rpc_wallet_proto_rawDesc)))
	})
	return file_app_wallet_rpc_wallet_proto_rawDescData
}

var file_app_wallet_rpc_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_app_wallet_rpc_wallet_proto_goTypes = []any{
	(*CreateWalletReq)(nil),  // 0: wallet.CreateWalletReq
	(*CreateWalletResp)(nil), // 1: wallet.CreateWalletResp
	(*GetBalanceReq)(nil),    // 2: wallet.GetBalanceReq
	(*GetBalanceResp)(nil),   // 3: wallet.GetBalanceResp
	(*DepositReq)(nil),       // 4: wallet.DepositReq
	(*DepositResp)(nil),      // 5: wallet.DepositResp
	(*WithdrawReq)(nil),      // 6: wallet.WithdrawReq
	(*WithdrawResp)(nil),     // 7: wallet.WithdrawResp
}
var file_app_wallet_rpc_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.Wallet.CreateWallet:input_type -> wallet.CreateWalletReq
	2, // 1: wallet.Wallet.GetBalance:input_type -> wallet.GetBalanceReq
	4, // 2: wallet.Wallet.Deposit:input_type -> wallet.DepositReq
	6, // 3: wallet.Wallet.Withdraw:input_type -> wallet.WithdrawReq
	1, // 4: wallet.Wallet.CreateWallet:output_type -> wallet.CreateWalletResp
	3, // 5: wallet.Wallet.GetBalance:output_type -> wallet.GetBalanceResp
	5, // 6: wallet.Wallet.Deposit:output_type -> wallet.DepositResp
	7, // 7: wallet.Wallet.Withdraw:output_type -> wallet.WithdrawResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_wallet_rpc_wallet_proto_init() }
func file_app_wallet_rpc_wallet_proto_init() {
	if File_app_wallet_rpc_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_wallet_rpc_wallet_proto_rawDesc), len(file_app_wallet_rpc_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_wallet_rpc_wallet_proto_goTypes,
		DependencyIndexes: file_app_wallet_rpc_wallet_proto_depIdxs,
		MessageInfos:      file_app_wallet_rpc_wallet_proto_msgTypes,
	}.Build()
	File_app_wallet_rpc_wallet_proto = out.File
	file_app_wallet_rpc_wallet_proto_goTypes = nil
	file_app_wallet_rpc_wallet_proto_depIdxs = nil
}
