// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: app/wallet/rpc/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建钱包
type CreateWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletReq) Reset() {
	*x = CreateWalletReq{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletReq) ProtoMessage() {}

func (x *CreateWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletReq.ProtoReflect.Descriptor instead.
func (*CreateWalletReq) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWalletReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 返回地址
type CreateWalletResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResp) Reset() {
	*x = CreateWalletResp{}
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResp) ProtoMessage() {}

func (x *CreateWalletResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_wallet_rpc_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResp.ProtoReflect.Descriptor instead.
func (*CreateWalletResp) Descriptor() ([]byte, []int) {
	return file_app_wallet_rpc_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResp) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_app_wallet_rpc_wallet_proto protoreflect.FileDescriptor

const file_app_wallet_rpc_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1bapp/wallet/rpc/wallet.proto\x12\x06wallet\"#\n" +
	"\x0fCreateWalletReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\",\n" +
	"\x10CreateWalletResp\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress2K\n" +
	"\x06Wallet\x12A\n" +
	"\fCreateWallet\x12\x17.wallet.CreateWalletReq\x1a\x18.wallet.CreateWalletRespB\n" +
	"Z\b./walletb\x06proto3"

var (
	file_app_wallet_rpc_wallet_proto_rawDescOnce sync.Once
	file_app_wallet_rpc_wallet_proto_rawDescData []byte
)

func file_app_wallet_rpc_wallet_proto_rawDescGZIP() []byte {
	file_app_wallet_rpc_wallet_proto_rawDescOnce.Do(func() {
		file_app_wallet_rpc_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_wallet_rpc_wallet_proto_rawDesc), len(file_app_wallet_rpc_wallet_proto_rawDesc)))
	})
	return file_app_wallet_rpc_wallet_proto_rawDescData
}

var file_app_wallet_rpc_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_wallet_rpc_wallet_proto_goTypes = []any{
	(*CreateWalletReq)(nil),  // 0: wallet.CreateWalletReq
	(*CreateWalletResp)(nil), // 1: wallet.CreateWalletResp
}
var file_app_wallet_rpc_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.Wallet.CreateWallet:input_type -> wallet.CreateWalletReq
	1, // 1: wallet.Wallet.CreateWallet:output_type -> wallet.CreateWalletResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_wallet_rpc_wallet_proto_init() }
func file_app_wallet_rpc_wallet_proto_init() {
	if File_app_wallet_rpc_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_wallet_rpc_wallet_proto_rawDesc), len(file_app_wallet_rpc_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_wallet_rpc_wallet_proto_goTypes,
		DependencyIndexes: file_app_wallet_rpc_wallet_proto_depIdxs,
		MessageInfos:      file_app_wallet_rpc_wallet_proto_msgTypes,
	}.Build()
	File_app_wallet_rpc_wallet_proto = out.File
	file_app_wallet_rpc_wallet_proto_goTypes = nil
	file_app_wallet_rpc_wallet_proto_depIdxs = nil
}
